/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DisenoGUIs.GUIsCUIAgregarPrenda;

import com.mycompany.dto_negocio.RopaTallaDTO;

/**
 * Panel que representa la tarjeta visual de un producto individual en el catálogo.
 * <p>
 * Este componente se utiliza dinámicamente para renderizar cada ítem de la lista de ropa.
 * Muestra información clave como el nombre, precio, talla y stock disponible.
 * Expone sus botones de acción (Editar y Eliminar) para que el controlador o la ventana principal
 * puedan asignarles el comportamiento específico.
 * </p>
 *
 * @author garfi
 * @version 1.0
 */
public class panelPrenda extends javax.swing.JPanel {

    /**
     * Constructor del panel.
     * Inicializa los componentes gráficos (labels, botones, colores de fondo).
     */
    public panelPrenda() {
        initComponents();
    }

    /**
     * Rellena la tarjeta con la información de un producto específico.
     * <p>
     * Actualiza las etiquetas de texto con los datos provenientes del DTO.
     * Si el producto tiene una talla asignada, concatena el nombre de la talla al nombre del artículo
     * (ej. "Camisa (M)").
     * </p>
     * * @param producto El objeto {@code RopaTallaDTO} que contiene los datos a visualizar.
     */
    public void setDatos(RopaTallaDTO producto) {

        if (producto.getRopa() != null) {
            String nombre = producto.getRopa().getNombreArticulo();
            lblPrecio.setText("$ " + String.valueOf(producto.getRopa().getPrecio()));

            if (producto.getTalla() != null) {
                nombre += " (" + producto.getTalla().getNombreTalla() + ")";
            }

            lblNombre.setText(nombre);
            lblPrecio.setText("$ " + producto.getRopa().getPrecio());
            // TODO: Implementar la carga de imagen desde ruta o bytes
        }
        lblStock.setText(String.valueOf(producto.getCantidad()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImg = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 213, 223));
        setPreferredSize(new java.awt.Dimension(164, 182));

        lblNombre.setText("Nombre Prenda");

        lblPrecio.setText("$$$");

        btnEditar.setBackground(new java.awt.Color(226, 115, 150));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(226, 115, 150));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel1.setText("Stock");

        lblStock.setText("123");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditar)
                        .addGap(7, 7, 7)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblStock)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(lblStock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addGap(7, 7, 7))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblStock;
    // End of variables declaration//GEN-END:variables

    
    /**
     * Obtiene la referencia al botón "Editar" de esta tarjeta.
     * <p>
     * Permite que el contenedor padre agregue un {@code ActionListener} personalizado
     * para manejar la lógica de edición de este ítem específico.
     * </p>
     * * @return El componente {@code JButton} de edición.
     */
    public javax.swing.JButton getBtnEditar() {
        return btnEditar;
    }

    /**
     * Obtiene la referencia al botón "Eliminar" de esta tarjeta.
     * <p>
     * Permite que el contenedor padre agregue un {@code ActionListener} personalizado
     * para manejar la lógica de eliminación de este ítem específico.
     * </p>
     * * @return El componente {@code JButton} de eliminación.
     */
    public javax.swing.JButton getBtnEliminar() {
        return btnEliminar;
    }
}
