/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUIsCUIAdminTendenciaSugerencia;

/**
 *
 * @author garfi
 */
public class panelSugerencia extends javax.swing.JPanel {

    /**
     * Creates new form panelSugerencia
     */
    public panelSugerencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAsunto = new javax.swing.JLabel();
        btnDetalles = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 213, 223));

        lblAsunto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblAsunto.setText("Asunto");

        btnDetalles.setBackground(new java.awt.Color(226, 115, 150));
        btnDetalles.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDetalles.setText("Ver detalles");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Estado:");

        lblEstado.setText("estado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(btnDetalles))
                    .addComponent(lblAsunto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAsunto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetalles)
                    .addComponent(jLabel2)
                    .addComponent(lblEstado))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalles;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAsunto;
    private javax.swing.JLabel lblEstado;
    // End of variables declaration//GEN-END:variables
}
