/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUIsCUIAdminTendenciaSugerencia;

import com.mycompany.dto_negocio.SugerenciaDTO;
import javax.swing.JButton;

/**
 * Panel que representa la tarjeta de resumen visual para una Sugerencia individual.
 * <p>
 * Este componente es utilizado por la ventana {@code GUIMenuSugerencia} para mostrar 
 * una lista filtrada de sugerencias, presentando la información esencial (fecha y estado) 
 * y un botón para navegar a los detalles completos.
 * </p>
 *
 * @author garfi
 * @version 1.0
 */
public class panelSugerencia extends javax.swing.JPanel {

    /** Almacena la referencia al objeto de transferencia de datos de la sugerencia que se está visualizando. */
    private SugerenciaDTO sugerenciaActual;
    
    /**
     * Constructor del panel.
     * Inicializa los componentes gráficos generados por el editor de formularios.
     */
    public panelSugerencia() {
        initComponents();
    }

    /**
     * Carga y actualiza las etiquetas del panel con la información del DTO.
     * * @param sugerencia El objeto {@code SugerenciaDTO} con los datos a visualizar.
     */
    public void setDatos(SugerenciaDTO sugerencia) {
        this.sugerenciaActual = sugerencia;
        
        // Muestra la fecha de publicación
        if (sugerencia.getFechaPublicacion() != null) {
            lblFecha.setText(sugerencia.getFechaPublicacion().toString());
        } else {
             lblFecha.setText("-");
        }
        
        lblEstado.setText(sugerencia.getEstado());
        
    }
    
    /**
     * Obtiene la referencia al botón "Ver detalles".
     * <p>
     * Este método es utilizado por la ventana principal ({@code GUIMenuSugerencia}) para 
     * asignar dinámicamente un {@code ActionListener} que navega a la vista de detalles
     * al hacer clic.
     * </p>
     * * @return El componente {@code JButton} de ver detalles.
     */
    public JButton getBtnDetalles() {
        return btnDetalles;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        btnDetalles = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 213, 223));

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl1.setText("Fecha de publicación:");

        btnDetalles.setBackground(new java.awt.Color(226, 115, 150));
        btnDetalles.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDetalles.setText("Ver detalles");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Estado:");

        lblEstado.setText("estado");

        lblFecha.setText("fecha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(btnDetalles))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFecha)
                        .addGap(33, 33, 33)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(lblFecha))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(btnDetalles)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblEstado))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalles;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFecha;
    // End of variables declaration//GEN-END:variables
}
