/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUICapacitacion;

import ControlPantallas.ControlGuiaInteractivaEmpleado;
import com.mycompany.dto_negocio.CapacitacionDTO;
import com.mycompany.dto_negocio.EmpleadoDTO;

/**
 *
 * @author riosr
 */
public class GUIMenuGuia extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenuGuia
     */
    private EmpleadoDTO empleado;
    
    /**
     * Creates new form GUIMenuGuia
     */
    public GUIMenuGuia(EmpleadoDTO empleado) {
        this.empleado = empleado;
        initComponents();
        
        
    }
    
    private void llenarEmpleado(){
        lblNombreEmpleado.setText(empleado.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNombreEmpleado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        btnGuiaAgregarPrenda = new javax.swing.JButton();
        btnGuiaDevolverPrenda = new javax.swing.JButton();
        btnGuiaManejoRobos = new javax.swing.JButton();
        btnGuiaClientesAgresivos = new javax.swing.JButton();
        btnVerCapacitaciones = new javax.swing.JButton();
        btnGuiaEmergenciasMedicas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(234, 154, 178));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Cuidado con el Kitten");

        jLabel3.setText("\n");

        lblNombreEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombreEmpleado.setText("Nombre Empleado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(lblNombreEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNombreEmpleado)
                        .addGap(19, 19, 19))))
        );

        jPanel2.setBackground(new java.awt.Color(255, 238, 242));

        btnVolver.setBackground(new java.awt.Color(239, 207, 227));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnGuiaAgregarPrenda.setBackground(new java.awt.Color(239, 207, 227));
        btnGuiaAgregarPrenda.setText("Agregar Prendas");
        btnGuiaAgregarPrenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiaAgregarPrendaActionPerformed(evt);
            }
        });

        btnGuiaDevolverPrenda.setBackground(new java.awt.Color(239, 207, 227));
        btnGuiaDevolverPrenda.setText("Devolver Prendas");
        btnGuiaDevolverPrenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiaDevolverPrendaActionPerformed(evt);
            }
        });

        btnGuiaManejoRobos.setBackground(new java.awt.Color(239, 207, 227));
        btnGuiaManejoRobos.setText("Manejo de Robos");
        btnGuiaManejoRobos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiaManejoRobosActionPerformed(evt);
            }
        });

        btnGuiaClientesAgresivos.setBackground(new java.awt.Color(239, 207, 227));
        btnGuiaClientesAgresivos.setText("Clientes Agresivos");
        btnGuiaClientesAgresivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiaClientesAgresivosActionPerformed(evt);
            }
        });

        btnVerCapacitaciones.setBackground(new java.awt.Color(239, 207, 227));
        btnVerCapacitaciones.setText("Capacitaciones");
        btnVerCapacitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCapacitacionesActionPerformed(evt);
            }
        });

        btnGuiaEmergenciasMedicas.setBackground(new java.awt.Color(239, 207, 227));
        btnGuiaEmergenciasMedicas.setText("Emergencias Medicas");
        btnGuiaEmergenciasMedicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiaEmergenciasMedicasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(btnGuiaEmergenciasMedicas, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnGuiaManejoRobos, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuiaAgregarPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuiaClientesAgresivos, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(btnVerCapacitaciones)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuiaDevolverPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnVolver)
                                .addGap(21, 21, 21)))))
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuiaDevolverPrenda)
                    .addComponent(btnGuiaClientesAgresivos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuiaManejoRobos)
                    .addComponent(btnGuiaAgregarPrenda))
                .addGap(43, 43, 43)
                .addComponent(btnGuiaEmergenciasMedicas)
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnVerCapacitaciones))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        //        ControlPantallas.getInstase().getControlReembolso().cancelar(this);

        ControlPantallas.ControlPantallas.getInstase().navegarMenuPrincipal(this, empleado);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnGuiaAgregarPrendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiaAgregarPrendaActionPerformed
        // TODO add your handling code here:
        CapacitacionDTO  capacitacion = ControlGuiaInteractivaEmpleado.getIntase().getGuiaInteractiva().capacitacionTema(empleado, "agregarStock");
        ControlGuiaInteractivaEmpleado.getIntase().navegarGUIGuiaAgregarPrenda1(this, empleado, capacitacion);

    }//GEN-LAST:event_btnGuiaAgregarPrendaActionPerformed

    private void btnGuiaDevolverPrendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiaDevolverPrendaActionPerformed
        // TODO add your handling code here:
        CapacitacionDTO  capacitacion = ControlGuiaInteractivaEmpleado.getIntase().getGuiaInteractiva().capacitacionTema(empleado, "devolverPrenda");
        ControlGuiaInteractivaEmpleado.getIntase().navegarGUIGuiaDevolverPrenda1(this, empleado, capacitacion);
    }//GEN-LAST:event_btnGuiaDevolverPrendaActionPerformed

    private void btnGuiaManejoRobosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiaManejoRobosActionPerformed
        // TODO add your handling code here:
        CapacitacionDTO  capacitacion = ControlGuiaInteractivaEmpleado.getIntase().getGuiaInteractiva().capacitacionTema(empleado, "robos");
        ControlGuiaInteractivaEmpleado.getIntase().navegarGUIRobosOAmenazasCooperar(this, empleado, capacitacion);

    }//GEN-LAST:event_btnGuiaManejoRobosActionPerformed

    private void btnGuiaClientesAgresivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiaClientesAgresivosActionPerformed
        // TODO add your handling code here:
        CapacitacionDTO  capacitacion = ControlGuiaInteractivaEmpleado.getIntase().getGuiaInteractiva().capacitacionTema(empleado, "agresividad");
        ControlGuiaInteractivaEmpleado.getIntase().navegarGUIClientesAgresivosMantenerCalma(this, empleado, capacitacion);
    }//GEN-LAST:event_btnGuiaClientesAgresivosActionPerformed

    private void btnVerCapacitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCapacitacionesActionPerformed
        // TODO add your handling code here:

        ControlGuiaInteractivaEmpleado.getIntase().navegarGUIVerCapacitaciones(this, empleado);
    }//GEN-LAST:event_btnVerCapacitacionesActionPerformed

    private void btnGuiaEmergenciasMedicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiaEmergenciasMedicasActionPerformed
        // TODO add your handling code here:
        CapacitacionDTO  capacitacion = ControlGuiaInteractivaEmpleado.getIntase().getGuiaInteractiva().capacitacionTema(empleado, "emergenciaMedica");
        ControlGuiaInteractivaEmpleado.getIntase().navegarGUIEmergenciaMedicaGararantizaSeguridad(this, empleado, capacitacion);
    }//GEN-LAST:event_btnGuiaEmergenciasMedicasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMenuGuia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMenuGuia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMenuGuia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMenuGuia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuiaAgregarPrenda;
    private javax.swing.JButton btnGuiaClientesAgresivos;
    private javax.swing.JButton btnGuiaDevolverPrenda;
    private javax.swing.JButton btnGuiaEmergenciasMedicas;
    private javax.swing.JButton btnGuiaManejoRobos;
    private javax.swing.JButton btnVerCapacitaciones;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNombreEmpleado;
    // End of variables declaration//GEN-END:variables
}
