/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DisenoGUIs;

import ControlPantallas.ControlPantallas;
import com.mycompany.dto_negocio.DetalleVentaDTO;

/**
 *
 * @author santi
 */
public class JProductoPanel extends javax.swing.JPanel {

    /**
     * Creates new form JProductoPanel
     */
    DetalleVentaDTO detalle;
    
    public JProductoPanel(DetalleVentaDTO detalle) {
        initComponents();
        this.detalle = detalle;
        llenarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        lblNombrePrenda = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblTalla = new javax.swing.JLabel();

        setBackground(new java.awt.Color(239, 207, 227));
        setPreferredSize(new java.awt.Dimension(423, 64));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/camisaPequeña.png"))); // NOI18N

        lblNombrePrenda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombrePrenda.setText("Nombre prenda");

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPrecio.setText("Precio");

        lblTalla.setText("Talla");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTalla)
                    .addComponent(lblNombrePrenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(lblPrecio)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombrePrenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTalla)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblPrecio)
                        .addGap(17, 17, 17))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void llenarDatos(){
        lblNombrePrenda.setText(detalle.getRopaTalla().getRopa().getNombreArticulo());
        lblTalla.setText(detalle.getRopaTalla().getTalla().getNombreTalla());
        lblPrecio.setText(String.valueOf(detalle.getSubtotal()));
        if(detalle.getRopaTalla().getRopa().getUrlImagen() != null){
            ControlPantallas.getInstase().mostrarImagenEnLabel(detalle.getRopaTalla().getRopa().getUrlImagen(), jLabel5);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblNombrePrenda;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTalla;
    // End of variables declaration//GEN-END:variables
}
