/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AsignarHorario;

import ControlPantallas.ControlEmpleados;
import DisenoGUIs.*;
import ControlPantallas.ControlPantallas;
import com.mycompany.dto_negocio.DiaHorarioDTO;
import com.mycompany.dto_negocio.EmpleadoDTO;
import com.mycompany.dto_negocio.HorarioDTO;
import java.time.DayOfWeek;
import java.time.LocalTime;
import javax.swing.JTable;

/**
 *
 * @author emiim
 */
public class GUIAsignarHorarios extends javax.swing.JFrame {

    /**
     * Creates new form GUICodigoProducto
     * 
     */
    private EmpleadoDTO empleado;
    
    public GUIAsignarHorarios(EmpleadoDTO empleado) {
        initComponents();
        this.empleado = empleado;
        if(empleado.getHorario() == null){
            HorarioDTO horario = new HorarioDTO();
            empleado.setHorario(horario);
        }
        llenarEmpleado();
        configurarTablaHorario(jTable1, empleado.getHorario());
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnCatalogo = new javax.swing.JButton();
        btnInfrestructura = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        nombreTxt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        salarioTxt1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        puestoTxt3 = new javax.swing.JLabel();
        telefonoTxt2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        emailTxt4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnRegresar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(234, 154, 178));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gatoLogo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Cuidado con el Kitten");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(23, 23, 23))
        );

        jPanel2.setBackground(new java.awt.Color(255, 238, 242));

        jPanel3.setBackground(new java.awt.Color(179, 222, 226));

        btnCatalogo.setBackground(new java.awt.Color(239, 207, 227));
        btnCatalogo.setText("Catagolo");
        btnCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogoActionPerformed(evt);
            }
        });

        btnInfrestructura.setBackground(new java.awt.Color(239, 207, 227));
        btnInfrestructura.setText("Infrestructura");
        btnInfrestructura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfrestructuraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInfrestructura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCatalogo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnCatalogo)
                .addGap(18, 18, 18)
                .addComponent(btnInfrestructura)
                .addContainerGap(374, Short.MAX_VALUE))
        );

        btnRegresar.setBackground(new java.awt.Color(234, 154, 178));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(234, 154, 178));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAgregar.setText("Asignar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nombreTxt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nombreTxt.setText("Nombre empleado");

        jLabel6.setText("Imagen");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Salario");

        salarioTxt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        salarioTxt1.setText("00");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Puesto:");

        puestoTxt3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        puestoTxt3.setText("cajero");

        telefonoTxt2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telefonoTxt2.setText("+52 6444-444-444");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Telefono:");

        emailTxt4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailTxt4.setText("hola@ejemploc.com");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Correo:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nombreTxt)
                .addGap(20, 20, 20))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel10))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salarioTxt1)
                    .addComponent(telefonoTxt2)
                    .addComponent(emailTxt4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(puestoTxt3)
                .addGap(55, 55, 55))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreTxt)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(puestoTxt3)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel6)))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(emailTxt4))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(telefonoTxt2))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(salarioTxt1))
                .addGap(18, 28, Short.MAX_VALUE))
        );

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"7:00-8:00", null, null, null, null, null, null, null},
                {"8:00-9:00", null, null, null, null, null, null, null},
                {"9:00-10:00", null, null, null, null, null, null, null},
                {"10:00-11:00", null, null, null, null, null, null, null},
                {"11:00-12:00", null, null, null, null, null, null, null},
                {"12:00-13:00", null, null, null, null, null, null, null},
                {"13:00-14:00", null, null, null, null, null, null, null},
                {"14:00-15:00", null, null, null, null, null, null, null},
                {"15:00-16:00", null, null, null, null, null, null, null},
                {"16:00-17:00", null, null, null, null, null, null, null},
                {"17:00-18:00", null, null, null, null, null, null, null},
                {"18:00-19:00", null, null, null, null, null, null, null},
                {"19:00-20:00", null, null, null, null, null, null, null},
                {"20:00-21:00", null, null, null, null, null, null, null}
            },
            new String [] {
                "Horas", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        btnRegresar1.setBackground(new java.awt.Color(234, 154, 178));
        btnRegresar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegresar1.setText("Limpiar");
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregar)
                        .addGap(56, 56, 56))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRegresar1)
                                .addGap(36, 36, 36)))
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRegresar1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegresar)
                            .addComponent(btnAgregar)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCatalogoActionPerformed

    private void btnInfrestructuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfrestructuraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInfrestructuraActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        ControlEmpleados.getInstase().navegarEmpleados(this);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        System.out.println(empleado.getHorario().getDias());
        ControlEmpleados.getInstase().getManejadorEmpleados().modificarEmpleado(empleado);
        ControlEmpleados.getInstase().navegarEmpleados(this);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        // TODO add your handling code here:
        empleado.setHorario(new HorarioDTO());
        configurarTablaHorario(jTable1, empleado.getHorario());
        
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCatalogo;
    private javax.swing.JButton btnInfrestructura;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JLabel emailTxt4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nombreTxt;
    private javax.swing.JLabel puestoTxt3;
    private javax.swing.JLabel salarioTxt1;
    private javax.swing.JLabel telefonoTxt2;
    // End of variables declaration//GEN-END:variables

    private void llenarEmpleado(){
        nombreTxt.setText(empleado.getNombre());
        emailTxt4.setText(empleado.getEmail());
        telefonoTxt2.setText(empleado.getTelefono());
        puestoTxt3.setText(empleado.getTelefono());
        salarioTxt1.setText(String.valueOf(empleado.getSalario()));     
    }

   
   private void configurarTablaHorario(JTable tabla, HorarioDTO horarioActual) {

        String[] columnas = { "Hora", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado" };

        java.util.List<String> horas = new java.util.ArrayList<>();
        java.time.LocalTime inicio = java.time.LocalTime.of(9, 0);
        java.time.LocalTime fin = java.time.LocalTime.of(22, 0);
        while (!inicio.isAfter(fin)) {
            horas.add(inicio.toString());
            inicio = inicio.plusMinutes(30);
        }

        Object[][] datos = new Object[horas.size()][columnas.length];
        for (int i = 0; i < horas.size(); i++) {
            datos[i][0] = horas.get(i); // primera columna = hora
        }

        // Modelo de tabla
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(datos, columnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabla.setModel(modelo);
        tabla.setRowHeight(25);

        // Variables temporales de selección
        final Integer[] filaInicio = { null };
        final Integer[] filaFin = { null };
        final Integer[] columnaSeleccionada = { null };

        // Mantener los rangos seleccionados para pintar
        java.util.Map<Integer, java.util.List<int[]>> rangosPintados = new java.util.HashMap<>();
        for (int c = 1; c < columnas.length; c++) {
            rangosPintados.put(c, new java.util.ArrayList<>());
        }

        // Inicializar rangosPintados con los horarios existentes en horarioActual
        for (DiaHorarioDTO dh : horarioActual.getDias()) {
            int columna = dh.getDia().getValue(); // MONDAY=1, TUESDAY=2, etc.
            int filaInicioRango = -1, filaFinRango = -1;
            for (int i = 0; i < horas.size(); i++) {
                LocalTime h = LocalTime.parse(horas.get(i));
                if (!h.isBefore(dh.getHoraEntrada()) && filaInicioRango == -1) filaInicioRango = i;
                if (!h.isAfter(dh.getHoraSalida())) filaFinRango = i;
            }
            if (filaInicioRango != -1 && filaFinRango != -1) {
                rangosPintados.get(columna).add(new int[]{filaInicioRango, filaFinRango});
            }
        }

        // Renderer
        javax.swing.table.DefaultTableCellRenderer renderer = new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                if (column == 0) {
                    setBackground(java.awt.Color.LIGHT_GRAY); // columna de horas
                } else {
                    boolean pintado = false;
                    for (int[] rango : rangosPintados.get(column)) {
                        if (row >= rango[0] && row <= rango[1]) {
                            pintado = true;
                            break;
                        }
                    }
                    setBackground(pintado ? java.awt.Color.CYAN : java.awt.Color.WHITE);
                }
                return this;
            }
        };
        tabla.setDefaultRenderer(Object.class, renderer);

        // Listener para seleccionar rango de horas
        tabla.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int fila = tabla.getSelectedRow();
                int columna = tabla.getSelectedColumn();

                if (fila == -1 || columna <= 0) return; // ignorar columna de horas

                if (columnaSeleccionada[0] == null) {
                    columnaSeleccionada[0] = columna;
                    filaInicio[0] = fila;
                    filaFin[0] = null;
                    return;
                }

                if (columna != columnaSeleccionada[0]) {
                    columnaSeleccionada[0] = columna;
                    filaInicio[0] = fila;
                    filaFin[0] = null;
                    return;
                }

                filaFin[0] = fila;

                int start = Math.min(filaInicio[0], filaFin[0]);
                int end = Math.max(filaInicio[0], filaFin[0]);

                // Crear DiaHorarioDTO
                DayOfWeek dia = DayOfWeek.of(columna); // columna 1 = lunes
                LocalTime horaEntrada = LocalTime.parse((String) tabla.getValueAt(start, 0));
                LocalTime horaSalida = LocalTime.parse((String) tabla.getValueAt(end, 0));

                DiaHorarioDTO dh = new DiaHorarioDTO();
                dh.setDia(dia);
                dh.setHoraEntrada(horaEntrada);
                dh.setHoraSalida(horaSalida);

                // Agregar al Horario actual
                horarioActual.getDias().add(dh);

                // Guardar el rango para pintar permanentemente
                // Reemplazar el rango anterior del día
                rangosPintados.get(columna).clear();

                // Guardar el único rango válido
                rangosPintados.get(columna).add(new int[]{start, end});


                // Limpiar selección temporal
                filaInicio[0] = null;
                filaFin[0] = null;
                columnaSeleccionada[0] = null;

                // Repintar tabla
                tabla.repaint();

                System.out.println("Horario agregado: " + dia + " " + horaEntrada + " - " + horaSalida);
            }
        });

        // Repintar inicialmente para mostrar horarios existentes
        tabla.repaint();
    }

    private void configurarNavegacionPerfil() {
        final ControlPantallas navegador = ControlPantallas.getInstase();  
    }
}

